### ISSUE TITLE
Definujte blíže disky/úložiště

### ISSUE THREAD

**Issue by Bahamut731lp** [Bahamut731lp/PDO#10]

**Comment by Tach3** [comment]
Disk:

Existujú rôzne typy diskov, ako napríklad pevné disky (hard disk drives - HDD), ktoré používajú magnetické disky na ukladanie dát, alebo pevné disky s polovodičovými pamäťami (solid-state drives - SSD), ktoré používajú polovodičové pamäte. Disky môžu byť interné, umiestnené priamo v počítači, alebo externé, pripojené k počítaču pomocou rozhraní ako USB. Disky sú často používané na trvalé ukladanie dát, ktoré majú byť dlhodobo dostupné a uchované.

Úložisko:

Úložisko je širší termín, ktorý zahŕňa akékoľvek médium alebo zariadenie, ktoré umožňuje ukladanie dát. Okrem diskov môžu úložiská zahŕňať napríklad flash disky, pamäťové karty, CD/DVD disky, cloudové úložiská a ďalšie. Úložiská môžu byť používané na dočasné ukladanie dát alebo na zálohovanie a archiváciu dôležitých informácií. Ich účelom je poskytnúť spôsob, ako uchovať a neskôr obnoviť dáta, keď je to potrebné.
